version: '3'
services:
  app:
    container_name: wishlist-api
    restart: always
    build: .
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '3000:3000'
  postgres:
    container_name: postgresql
    hostname: postgres
    image: postgres:10.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: wishlist
    ports:
      - '5432:5432'